services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "imdb"
      PGUSER: "postgres"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready'"]
      interval: 10s
      timeout: 3s
      retries: 3


  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080


  fuseki:
    #command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    image: fuseki
    build: 
      context: ./fuseki
      dockerfile: Dockerfile
      args:
        JENA_VERSION: 6.0.0
    container_name: fuseki
    ports:
      - 3030:3030
    volumes:
      - ./fuseki/logs:/fuseki/logs
      - ./fuseki/databases:/fuseki/databases
    depends_on:
      java:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:3030/$/ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m


  python:
    #image: python:latest
    build: python
    container_name: python
    depends_on:
      fuseki:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/data:ro

  java:
    build: java
    container_name: java
    volumes:
      - ./data:/data:ro
      - fusekidata:/fusekidata


volumes:
    pgdata:
    fusekidata:
